### ISSUE TITLE
spy doesn't work inside an "it" block

### ISSUE THREAD

**Issue by djha-skin** [cloojure/tupelo#10]
I have the equivalent of something like this in my code:

```clojure
(def a [{:a 1 :b 2}
           {:c 3 :d 4}])
(tupelo/it-> a
    (tupelo/spy (first it) :msg "it sample")
    (tupelo/spy it :msg "it has changed"))
```

This prints:

```
it sample => {:a 1 :b 2}
it has changed => {:a 1 :b 2}
```

and returns:

```
{:a 1 :b 2}
```

But it should print:

```
it sample => {:a 1 :b 2}
it has changed => [{:a 1 :b 2} {:c 1 :d 2}]
```

and return:

```
[{:a 1 :b 2} {:c 1 :d 2}]
```

Should it not?

**Comment by djha-skin** [comment]
Ah, just got it, you wrap whatever you're spy'ing on with `spy`, so this works as intended. Nevermind :)

**Comment by cloojure** [comment]
OK, let me know if anything else comes up!
Alan

On Sat, Apr 29, 2017 at 4:56 PM, Daniel Jay Haskin <notifications@github.com
