### ISSUE TITLE
resolve-var does not exist

### ISSUE THREAD

**Issue by akond** [cloojure/tupelo#11]
As soon as I run `(require '[tupelo.core :as t])` I get this exception:
CompilerException java.lang.IllegalAccessError: resolve-var does not exist, compiling:(clojure/tools/analyzer/jvm.clj:1:1) 

> #error{:cause "resolve-var does not exist",
>        :via [{:type clojure.lang.Compiler$CompilerException,
>               :message "java.lang.IllegalAccessError: resolve-var does not exist, compiling:(clojure/tools/analyzer/jvm.clj:1:1)",
>               :at [clojure.lang.Compiler load "Compiler.java" 7526]}
>              {:type java.lang.IllegalAccessError,
>               :message "resolve-var does not exist",
>               :at [clojure.core$refer invokeStatic "core.clj" 4215]}],
>        :trace [[clojure.core$refer invokeStatic "core.clj" 4215]
>                [clojure.core$refer doInvoke "core.clj" 4183]
>                [clojure.lang.RestFn applyTo "RestFn.java" 139]
>                [clojure.core$apply invokeStatic "core.clj" 659]
>                [clojure.core$load_lib invokeStatic "core.clj" 5906]
>                [clojure.core$load_lib doInvoke "core.clj" 5868]
>                [clojure.lang.RestFn applyTo "RestFn.java" 142]
>                [clojure.core$apply invokeStatic "core.clj" 659]
>                [clojure.core$load_libs invokeStatic "core.clj" 5929]
>                [clojure.core$load_libs doInvoke "core.clj" 5909]
>                [clojure.lang.RestFn applyTo "RestFn.java" 137]
>                [clojure.core$apply invokeStatic "core.clj" 659]
>                [clojure.core$require invokeStatic "core.clj" 5947]
>                [clojure.core$require doInvoke "core.clj" 5947]
>                [clojure.lang.RestFn invoke "RestFn.java" 512]
>                [clojure.tools.analyzer.jvm$eval5562$loading__6434__auto____5563 invoke "jvm.clj" 9]
>                [clojure.tools.analyzer.jvm$eval5562 invokeStatic "jvm.clj" 9]
>                [clojure.tools.analyzer.jvm$eval5562 invoke "jvm.clj" 9]
>                [clojure.lang.Compiler eval "Compiler.java" 7062]
>                [clojure.lang.Compiler eval "Compiler.java" 7051]
>                [clojure.lang.Compiler load "Compiler.java" 7514]
>                [clojure.lang.RT loadResourceScript "RT.java" 379]
>                [clojure.lang.RT loadResourceScript "RT.java" 370]
>                [clojure.lang.RT load "RT.java" 460]
>                [clojure.lang.RT load "RT.java" 426]
>                [clojure.core$load$fn__6548 invoke "core.clj" 6046]
>                [clojure.core$load invokeStatic "core.clj" 6045]
>                [clojure.core$load doInvoke "core.clj" 6029]
>                [clojure.lang.RestFn invoke "RestFn.java" 408]
>                [clojure.core$load_one invokeStatic "core.clj" 5848]
>                [clojure.core$load_one invoke "core.clj" 5843]
>                [clojure.core$load_lib$fn__6493 invoke "core.clj" 5888]
>                [clojure.core$load_lib invokeStatic "core.clj" 5887]
>                [clojure.core$load_lib doInvoke "core.clj" 5868]
>                [clojure.lang.RestFn applyTo "RestFn.java" 142]
>                [clojure.core$apply invokeStatic "core.clj" 659]
>                [clojure.core$load_libs invokeStatic "core.clj" 5925]
>                [clojure.core$load_libs doInvoke "core.clj" 5909]
>                [clojure.lang.RestFn applyTo "RestFn.java" 137]
>                [clojure.core$apply invokeStatic "core.clj" 659]
>                [clojure.core$require invokeStatic "core.clj" 5947]
>                [clojure.core$require doInvoke "core.clj" 5947]
>                [clojure.lang.RestFn invoke "RestFn.java" 930]
>                [clojure.core.async.impl.ioc_macros$eval4810$loading__6434__auto____4811 invoke "ioc_macros.clj" 12]
>                [clojure.core.async.impl.ioc_macros$eval4810 invokeStatic "ioc_macros.clj" 12]
>                [clojure.core.async.impl.ioc_macros$eval4810 invoke "ioc_macros.clj" 12]
>                [clojure.lang.Compiler eval "Compiler.java" 7062]
>                [clojure.lang.Compiler eval "Compiler.java" 7051]
>                [clojure.lang.Compiler load "Compiler.java" 7514]
>                [clojure.lang.RT loadResourceScript "RT.java" 379]
>                [clojure.lang.RT loadResourceScript "RT.java" 370]
>                [clojure.lang.RT load "RT.java" 460]
>                [clojure.lang.RT load "RT.java" 426]
>                [clojure.core$load$fn__6548 invoke "core.clj" 6046]
>                [clojure.core$load invokeStatic "core.clj" 6045]
>                [clojure.core$load doInvoke "core.clj" 6029]
>                [clojure.lang.RestFn invoke "RestFn.java" 408]
>                [clojure.core$load_one invokeStatic "core.clj" 5848]
>                [clojure.core$load_one invoke "core.clj" 5843]
>                [clojure.core$load_lib$fn__6493 invoke "core.clj" 5888]
>                [clojure.core$load_lib invokeStatic "core.clj" 5887]
>                [clojure.core$load_lib doInvoke "core.clj" 5868]
>                [clojure.lang.RestFn applyTo "RestFn.java" 142]
>                [clojure.core$apply invokeStatic "core.clj" 659]
>                [clojure.core$load_libs invokeStatic "core.clj" 5925]
>                [clojure.core$load_libs doInvoke "core.clj" 5909]
>                [clojure.lang.RestFn applyTo "RestFn.java" 137]
>                [clojure.core$apply invokeStatic "core.clj" 659]
>                [clojure.core$require invokeStatic "core.clj" 5947]
>                [clojure.core$require doInvoke "core.clj" 5947]
>                [clojure.lang.RestFn invoke "RestFn.java" 619]
>                [clojure.core.async$eval4200$loading__6434__auto____4201 invoke "async.clj" 9]
>                [clojure.core.async$eval4200 invokeStatic "async.clj" 9]
>                [clojure.core.async$eval4200 invoke "async.clj" 9]
>                [clojure.lang.Compiler eval "Compiler.java" 7062]
>                [clojure.lang.Compiler eval "Compiler.java" 7051]
>                [clojure.lang.Compiler load "Compiler.java" 7514]
>                [clojure.lang.RT loadResourceScript "RT.java" 379]
>                [clojure.lang.RT loadResourceScript "RT.java" 370]
>                [clojure.lang.RT load "RT.java" 460]
>                [clojure.lang.RT load "RT.java" 426]
>                [clojure.core$load$fn__6548 invoke "core.clj" 6046]
>                [clojure.core$load invokeStatic "core.clj" 6045]
>                [clojure.core$load doInvoke "core.clj" 6029]
>                [clojure.lang.RestFn invoke "RestFn.java" 408]
>                [clojure.core$load_one invokeStatic "core.clj" 5848]
>                [clojure.core$load_one invoke "core.clj" 5843]
>                [clojure.core$load_lib$fn__6493 invoke "core.clj" 5888]
>                [clojure.core$load_lib invokeStatic "core.clj" 5887]
>                [clojure.core$load_lib doInvoke "core.clj" 5868]
>                [clojure.lang.RestFn applyTo "RestFn.java" 142]
>                [clojure.core$apply invokeStatic "core.clj" 659]
>                [clojure.core$load_libs invokeStatic "core.clj" 5925]
>                [clojure.core$load_libs doInvoke "core.clj" 5909]
>                [clojure.lang.RestFn applyTo "RestFn.java" 137]
>                [clojure.core$apply invokeStatic "core.clj" 659]
>                [clojure.core$require invokeStatic "core.clj" 5947]
>                [clojure.core$require doInvoke "core.clj" 5947]
>                [clojure.lang.RestFn invoke "RestFn.java" 930]
>                [tupelo.impl$eval4192$loading__6434__auto____4193 invoke "impl.cljc" 7]
>                [tupelo.impl$eval4192 invokeStatic "impl.cljc" 7]
>                [tupelo.impl$eval4192 invoke "impl.cljc" 7]
>                [clojure.lang.Compiler eval "Compiler.java" 7062]
>                [clojure.lang.Compiler eval "Compiler.java" 7051]
>                [clojure.lang.Compiler load "Compiler.java" 7514]
>                [clojure.lang.RT loadResourceScript "RT.java" 379]
>                [clojure.lang.RT loadResourceScript "RT.java" 370]
>                [clojure.lang.RT load "RT.java" 460]
>                [clojure.lang.RT load "RT.java" 426]
>                [clojure.core$load$fn__6548 invoke "core.clj" 6046]
>                [clojure.core$load invokeStatic "core.clj" 6045]
>                [clojure.core$load doInvoke "core.clj" 6029]
>                [clojure.lang.RestFn invoke "RestFn.java" 408]
>                [clojure.core$load_one invokeStatic "core.clj" 5848]
>                [clojure.core$load_one invoke "core.clj" 5843]
>                [clojure.core$load_lib$fn__6493 invoke "core.clj" 5888]
>                [clojure.core$load_lib invokeStatic "core.clj" 5887]
>                [clojure.core$load_lib doInvoke "core.clj" 5868]
>                [clojure.lang.RestFn applyTo "RestFn.java" 142]
>                [clojure.core$apply invokeStatic "core.clj" 659]
>                [clojure.core$load_libs invokeStatic "core.clj" 5925]
>                [clojure.core$load_libs doInvoke "core.clj" 5909]
>                [clojure.lang.RestFn applyTo "RestFn.java" 137]
>                [clojure.core$apply invokeStatic "core.clj" 659]
>                [clojure.core$require invokeStatic "core.clj" 5947]
>                [clojure.core$require doInvoke "core.clj" 5947]
>                [clojure.lang.RestFn invoke "RestFn.java" 512]
>                [tupelo.core$eval1481$loading__6434__auto____1482 invoke "core.cljc" 7]
>                [tupelo.core$eval1481 invokeStatic "core.cljc" 7]
>                [tupelo.core$eval1481 invoke "core.cljc" 7]
>                [clojure.lang.Compiler eval "Compiler.java" 7062]
>                [clojure.lang.Compiler eval "Compiler.java" 7051]
>                [clojure.lang.Compiler load "Compiler.java" 7514]
>                [clojure.lang.RT loadResourceScript "RT.java" 379]
>                [clojure.lang.RT loadResourceScript "RT.java" 370]
>                [clojure.lang.RT load "RT.java" 460]
>                [clojure.lang.RT load "RT.java" 426]
>                [clojure.core$load$fn__6548 invoke "core.clj" 6046]
>                [clojure.core$load invokeStatic "core.clj" 6045]
>                [clojure.core$load doInvoke "core.clj" 6029]
>                [clojure.lang.RestFn invoke "RestFn.java" 408]
>                [clojure.core$load_one invokeStatic "core.clj" 5848]
>                [clojure.core$load_one invoke "core.clj" 5843]
>                [clojure.core$load_lib$fn__6493 invoke "core.clj" 5888]
>                [clojure.core$load_lib invokeStatic "core.clj" 5887]
>                [clojure.core$load_lib doInvoke "core.clj" 5868]
>                [clojure.lang.RestFn applyTo "RestFn.java" 142]
>                [clojure.core$apply invokeStatic "core.clj" 659]
>                [clojure.core$load_libs invokeStatic "core.clj" 5925]
>                [clojure.core$load_libs doInvoke "core.clj" 5909]
>                [clojure.lang.RestFn applyTo "RestFn.java" 137]
>                [clojure.core$apply invokeStatic "core.clj" 659]
>                [clojure.core$require invokeStatic "core.clj" 5947]
>                [clojure.core$require doInvoke "core.clj" 5947]
>                [clojure.lang.RestFn invoke "RestFn.java" 408]
>                [user$eval1475 invokeStatic "form-init8720017613240234783.clj" 1]
>                [user$eval1475 invoke "form-init8720017613240234783.clj" 1]
>                [clojure.lang.Compiler eval "Compiler.java" 7062]
>                [clojure.lang.Compiler eval "Compiler.java" 7025]
>                [clojure.core$eval invokeStatic "core.clj" 3206]
>                [clojure.core$eval invoke "core.clj" 3202]
>                [clojure.main$repl$read_eval_print__8572$fn__8575 invoke "main.clj" 243]
>                [clojure.main$repl$read_eval_print__8572 invoke "main.clj" 243]
>                [clojure.main$repl$fn__8581 invoke "main.clj" 261]
>                [clojure.main$repl invokeStatic "main.clj" 261]
>                [clojure.main$repl doInvoke "main.clj" 177]
>                [clojure.lang.RestFn invoke "RestFn.java" 1523]
>                [clojure.tools.nrepl.middleware.interruptible_eval$evaluate$fn__1122 invoke "interruptible_eval.clj" 87]
>                [clojure.lang.AFn applyToHelper "AFn.java" 152]
>                [clojure.lang.AFn applyTo "AFn.java" 144]
>                [clojure.core$apply invokeStatic "core.clj" 657]
>                [clojure.core$with_bindings_STAR_ invokeStatic "core.clj" 1965]
>                [clojure.core$with_bindings_STAR_ doInvoke "core.clj" 1965]
>                [clojure.lang.RestFn invoke "RestFn.java" 425]
>                [clojure.tools.nrepl.middleware.interruptible_eval$evaluate invokeStatic "interruptible_eval.clj" 85]
>                [clojure.tools.nrepl.middleware.interruptible_eval$evaluate invoke "interruptible_eval.clj" 55]
>                [clojure.tools.nrepl.middleware.interruptible_eval$interruptible_eval$fn__1167$fn__1170
>                 invoke
>                 "interruptible_eval.clj"
>                 222]
>                [clojure.tools.nrepl.middleware.interruptible_eval$run_next$fn__1162 invoke "interruptible_eval.clj" 190]
>                [clojure.lang.AFn run "AFn.java" 22]
>                [java.util.concurrent.ThreadPoolExecutor runWorker "ThreadPoolExecutor.java" 1142]
>                [java.util.concurrent.ThreadPoolExecutor$Worker run "ThreadPoolExecutor.java" 617]
>                [java.lang.Thread run "Thread.java" 745]]}

I assume it has something to do with core.async, but I can't wrap my head around it.

**Comment by catalan42** [comment]
Hi - I just tried to reproduce and it didn't fail:

~/expr > lein new app x20
Generating a project called x20 based on the 'app' template.
~/expr > cd x20
~/expr/x20 > gvim project.clj
~/expr/x20 > lein repl
nREPL server started on port 39742 on host 127.0.0.1 - nrepl://
127.0.0.1:39742
REPL-y 0.3.7, nREPL 0.2.12
Clojure 1.9.0
Java HotSpot(TM) 64-Bit Server VM 10.0.1+10
    Docs: (doc function-name-here)
          (find-doc "part-of-name-here")
  Source: (source function-name-here)
 Javadoc: (javadoc java-object-or-class-here)
    Exit: Control+D or (exit) or (quit)
 Results: Stored in vars *1, *2, *3, an exception in *e

x20.core=> (require '[tupelo.core :as t])
nil
x20.core=> (t/truthy? nil)
false
x20.core=> (t/truthy? 1)
true
x20.core=> Bye for now!
~/expr/x20 > lein --version
Leiningen 2.8.1 on Java 10.0.1 Java HotSpot(TM) 64-Bit Server VM
~/expr/x20 >



What os/jvm/tupelo version are you running?

Alan

On Sun, Aug 19, 2018 at 12:12 AM, Toropenko Sergey <notifications@github.com

**Comment by akond** [comment]
I run 
+ Windows 7 
+ Leiningen 2.8.1 on Java 1.8.0_66 Java HotSpot(TM) 64-Bit Server VM.
+ Clojure 1.9.0.

It's strange stuff. I created an empty project with two dependencies 
+ org.clojure/clojure "1.9.0"
+ tupelo "0.9.80"

When I execute `(:require [tupelo.core :as t])` in REPL or in otherwise empty namespace I get

> CompilerException java.lang.ClassNotFoundException: com.sun.tools.javac.util.Convert, compiling:(tupelo/core.cljc:1:1) 

> #error{:cause "com.sun.tools.javac.util.Convert",
>        :via [{:type clojure.lang.Compiler$CompilerException,
>               :message "java.lang.ClassNotFoundException: com.sun.tools.javac.util.Convert, compiling:(tupelo/core.cljc:1:1)",
>               :at [clojure.lang.Compiler load "Compiler.java" 7526]}
>              {:type java.lang.ClassNotFoundException,
>               :message "com.sun.tools.javac.util.Convert",
>               :at [java.net.URLClassLoader findClass "URLClassLoader.java" 381]}],
>        :trace [[java.net.URLClassLoader findClass "URLClassLoader.java" 381]
>                [clojure.lang.DynamicClassLoader findClass "DynamicClassLoader.java" 69]
>                [java.lang.ClassLoader loadClass "ClassLoader.java" 424]
>                [clojure.lang.DynamicClassLoader loadClass "DynamicClassLoader.java" 77]
>                [java.lang.ClassLoader loadClass "ClassLoader.java" 357]
>                [java.lang.Class forName0 "Class.java" -2]
>                [java.lang.Class forName "Class.java" 348]
>                [clojure.lang.RT classForName "RT.java" 2204]
>                [clojure.lang.RT classForNameNonLoading "RT.java" 2217]
>                [tupelo.core$eval1173$loading__6434__auto____1174 invoke "core.cljc" 7]
>                [tupelo.core$eval1173 invokeStatic "core.cljc" 7]
>                [tupelo.core$eval1173 invoke "core.cljc" 7]
>                [clojure.lang.Compiler eval "Compiler.java" 7062]
>                [clojure.lang.Compiler eval "Compiler.java" 7051]
>                [clojure.lang.Compiler load "Compiler.java" 7514]
>                [clojure.lang.RT loadResourceScript "RT.java" 379]
>                [clojure.lang.RT loadResourceScript "RT.java" 370]
>                [clojure.lang.RT load "RT.java" 460]
>                [clojure.lang.RT load "RT.java" 426]
>                [clojure.core$load$fn__6548 invoke "core.clj" 6046]
>                [clojure.core$load invokeStatic "core.clj" 6045]
>                [clojure.core$load doInvoke "core.clj" 6029]
>                [clojure.lang.RestFn invoke "RestFn.java" 408]
>                [clojure.core$load_one invokeStatic "core.clj" 5848]
>                [clojure.core$load_one invoke "core.clj" 5843]
>                [clojure.core$load_lib$fn__6493 invoke "core.clj" 5888]
>                [clojure.core$load_lib invokeStatic "core.clj" 5887]
>                [clojure.core$load_lib doInvoke "core.clj" 5868]
>                [clojure.lang.RestFn applyTo "RestFn.java" 142]
>                [clojure.core$apply invokeStatic "core.clj" 659]
>                [clojure.core$load_libs invokeStatic "core.clj" 5925]
>                [clojure.core$load_libs doInvoke "core.clj" 5909]
>                [clojure.lang.RestFn applyTo "RestFn.java" 137]
>                [clojure.core$apply invokeStatic "core.clj" 659]
>                [clojure.core$require invokeStatic "core.clj" 5947]
>                [clojure.core$require doInvoke "core.clj" 5947]
>                [clojure.lang.RestFn invoke "RestFn.java" 408]
>                [user$eval1167 invokeStatic "form-init5538161157951063692.clj" 1]
>                [user$eval1167 invoke "form-init5538161157951063692.clj" 1]
>                [clojure.lang.Compiler eval "Compiler.java" 7062]
>                [clojure.lang.Compiler eval "Compiler.java" 7025]
>                [clojure.core$eval invokeStatic "core.clj" 3206]
>                [clojure.core$eval invoke "core.clj" 3202]
>                [clojure.main$repl$read_eval_print__8572$fn__8575 invoke "main.clj" 243]
>                [clojure.main$repl$read_eval_print__8572 invoke "main.clj" 243]
>                [clojure.main$repl$fn__8581 invoke "main.clj" 261]
>                [clojure.main$repl invokeStatic "main.clj" 261]
>                [clojure.main$repl doInvoke "main.clj" 177]
>                [clojure.lang.RestFn invoke "RestFn.java" 1523]
>                [clojure.tools.nrepl.middleware.interruptible_eval$evaluate$fn__818 invoke "interruptible_eval.clj" 87]
>                [clojure.lang.AFn applyToHelper "AFn.java" 152]
>                [clojure.lang.AFn applyTo "AFn.java" 144]
>                [clojure.core$apply invokeStatic "core.clj" 657]
>                [clojure.core$with_bindings_STAR_ invokeStatic "core.clj" 1965]
>                [clojure.core$with_bindings_STAR_ doInvoke "core.clj" 1965]
>                [clojure.lang.RestFn invoke "RestFn.java" 425]
>                [clojure.tools.nrepl.middleware.interruptible_eval$evaluate invokeStatic "interruptible_eval.clj" 85]
>                [clojure.tools.nrepl.middleware.interruptible_eval$evaluate invoke "interruptible_eval.clj" 55]
>                [clojure.tools.nrepl.middleware.interruptible_eval$interruptible_eval$fn__863$fn__866
>                 invoke
>                 "interruptible_eval.clj"
>                 222]
>                [clojure.tools.nrepl.middleware.interruptible_eval$run_next$fn__858 invoke "interruptible_eval.clj" 190]
>                [clojure.lang.AFn run "AFn.java" 22]
>                [java.util.concurrent.ThreadPoolExecutor runWorker "ThreadPoolExecutor.java" 1142]
>                [java.util.concurrent.ThreadPoolExecutor$Worker run "ThreadPoolExecutor.java" 617]
>                [java.lang.Thread run "Thread.java" 745]]}
>

**Comment by cloojure** [comment]
Can you try java 9 or 10?  Perhaps that is the issue.  Also, I have not
tried it on windows for over a year.

**Comment by akond** [comment]
It works under java 10.
I've just tried.
The problem is the README file says in its requirement section it works under Java 1.8.

**Comment by cloojure** [comment]
Strange.  I know of nothing that would prevent it from working on Java 8.
I just got an error  too:

~/tupelo > lein test
Exception in thread "main" java.lang.ClassNotFoundException:
com.sun.tools.javac.util.Convert, compiling:(tupelo/core.cljc:1:1)
at clojure.lang.Compiler.load(Compiler.java:7526)
at clojure.lang.RT.loadResourceScript(RT.java:379)
at clojure.lang.RT.loadResourceScript(RT.java:370)
at clojure.lang.RT.load(RT.java:460)
at clojure.lang.RT.load(RT.java:426)
at clojure.core$load$fn__6548.invoke(core.clj:6046)
at clojure.core$load.invokeStatic(core.clj:6045)
at clojure.core$load.doInvoke(core.clj:6029)
at clojure.lang.RestFn.invoke(RestFn.java:408)
at clojure.core$load_one.invokeStatic(core.clj:5848)
at clojure.core$load_one.invoke(core.clj:5843)
at clojure.core$load_lib$fn__6493.invoke(core.clj:5888)
at clojure.core$load_lib.invokeStatic(core.clj:5887)
at clojure.core$load_lib.doInvoke(core.clj:5868)
at clojure.lang.RestFn.applyTo(RestFn.java:142)
at clojure.core$apply.invokeStatic(core.clj:659)
at clojure.core$load_libs.invokeStatic(core.clj:5925)
at clojure.core$load_libs.doInvoke(core.clj:5909)
at clojure.lang.RestFn.applyTo(RestFn.java:137)
at clojure.core$apply.invokeStatic(core.clj:659)
at clojure.core$require.invokeStatic(core.clj:5947)
at clojure.core$require.doInvoke(core.clj:5947)
at clojure.lang.RestFn.invoke(RestFn.java:421)
at
tst.tupelo._bootstrap$eval355$loading__6434__auto____356.invoke(_bootstrap.cljc:7)
at tst.tupelo._bootstrap$eval355.invokeStatic(_bootstrap.cljc:7)
at tst.tupelo._bootstrap$eval355.invoke(_bootstrap.cljc:7)
at clojure.lang.Compiler.eval(Compiler.java:7062)
with a different stacktrace (same initial problem with "Convert").  I'm not
sure where this could be coming from.  I did verify it works with Java 9
and 10.

Do you need to use Java 8?

Alan

**Comment by akond** [comment]
No, not really.
I switched to version 10.
But what about README?
Maybe you've compiled it under version 9 or 10 and it is not compatible with 8?

**Comment by cloojure** [comment]
Hi - I fixed the problem for Java 8.  It seems the IDE for some reason
included "import" for 2 weird Java classes that aren't even used (including
"Convert").  I removed the ":import" references and it works for java
8,9,10 now.

Just pushed 0.9.81

Alan

**Comment by akond** [comment]
This is great.
I confirm that it does work now for version 8.
