### ISSUE TITLE
classpath is polluted with extra files

### ISSUE THREAD

**Issue by hukka** [cloojure/tupelo#19]
Tupelo seems to include the images the README uses under resources, putting extra files into the jar file.

Even more surprising is that when using a web server for serving static files from the very common path "resources/public", tupelo includes the whole re-frame todomvc example, including the index.html file which will be served then.

**Comment by cloojure** [comment]
Hi - I'll see about rearranging things.  I haven't looked at that stuff in quite a while!

**Comment by cloojure** [comment]
Hi - I moved all the junk out of the `./resources` folder. The JAR file size shrank from 545KB => 170KB, about 70% savings.

**Comment by hukka** [comment]
resources/public is still populated though, so the second problem stands: default configurations start serving the re-frame todomvc demo, if anything in the project uses tupelo (even as a subdependency).

**Comment by catalan42** [comment]
Yes, I had that as a demo in CLJS which I still need to clean out.

**Comment by cloojure** [comment]
Cleaned out the cljs stuff. final size for JAR file is 165KB
