### ISSUE TITLE
Can't parse xml document if there is a comment after the XML decleration

### ISSUE THREAD

**Issue by ikappaki** [cloojure/tupelo#20]
Hi,

tupelo fails to parse an xml document when there is a comment just after the first line `<xml>` declaration:

```
Execution error (ExceptionInfo) at tupelo.core/only (core.cljc:684).
only: num-items must=1
```

I couldn't find anything in the literature to suggest this should fail, thus I expect it to work. The only relevant expected failure is when a comment is before the xml decleration: https://blog.submain.com/using-xml-comments/.

To reproduce, run the following

```clojure
(tupelo.parse.xml/parse "<?xml version=\"1.0\"?><!-- a comment --><xyz/>")
```

You should get the above exception.

Thanks

**Comment by cloojure** [comment]
Hi - I fixed the code to strip out all comments, so it works again.  See the 2 test cases:

https://github.com/cloojure/tupelo/blob/master/test/clj/tst/tupelo/parse/xml.clj#L151

Note, you forgot the "bang" in your example comment!  ;)

Deployed to Clojars already:   "22.08.03"

**Comment by ikappaki** [comment]
> Note, you forgot the "bang" in your example comment! ;)

Sorry my mistake, edited the original comment to the correct syntax.
 
> Deployed to Clojars already: "22.08.03"

Tested it to work, thanks!
