### ISSUE TITLE
Invalid regex pattern in cljc file

### ISSUE THREAD

**Issue by RolT** [cloojure/tupelo#21]
Hello,

I can't use the latest version of this library in cljs. I'm getting the following error:
```
Closure compilation failed with 1 errors
--- tupelo/core/impl.cljc:60
Parse error. Invalid RegExp flag 'x'
```

https://github.com/cloojure/tupelo/blob/9a1cf478bf71ad00c4e1067df565834bad69d41d/src/cljc/tupelo/core/impl.cljc
The regex here `#"(?x) ..."` is valid in java but not in JS.

**Comment by cloojure** [comment]
Hi - I pushed a new version that should resolve the issue.  Thanks for the report.

**Comment by RolT** [comment]
Thanks a lot, works fine now !
