### ISSUE TITLE
Make DatomicPro dependency optional

### ISSUE THREAD

**Issue by dlebrero** [cloojure/tupelo#3]
Right now tupelo.core depends on tupelo.schema which references the datomic.db.Db class which comes from the DatomicPro jar, which needs to be manually downloaded and installed. 

Could the DatomicPro dependency be made optional?

**Comment by cloojure** [comment]
That is a good question!  I have not played around with Datomic Free, which
would be the other option.  Obviously, either the Pro or the Free distro
would be required for Tupelo Datomic to make sense.

Maybe I just need to refactor the tupelo.schema class.  Let me look at that.

Alan

**Comment by cloojure** [comment]
Hi - Would you like to try version 0.1.55?  I removed the datomic
dependency into a difference ns, so I think that will fix it.  If not,
please let me know.

Thanks,
Alan

**Comment by dlebrero** [comment]
Works fine now. Thanks a lot!
