### ISSUE TITLE
Broken link in readme

### ISSUE THREAD

**Issue by andrenventer** [cloojure/tupelo#7]
https://github.com/cloojure/tupelo/blob/master/doc/csv.adoc

Tupelo CSV - Functions for using CSV (Comma Separate Value) files

The standard clojure-csv library has well-tested and useful functions for parsing CSV (Comma Separated Value) text data, but it does not offer all of the convenience one may wish. Tupelo CSV emphasizes the idomatic Clojure usage of data, using sequences and maps. Please see the tupelo.csv docs.

**Comment by cloojure** [comment]
Fixed! Thanks for the tip.  :)
