### ISSUE TITLE
Problem with `partition-using`

### ISSUE THREAD

**Issue by djha-skin** [cloojure/tupelo#8]
Hello!

I was introduced to tupelo in [this SO question](http://stackoverflow.com/questions/42881750/split-a-sequence-by-delimiter-in-clojure), glad to be here. The library looks super useful, like Boost for C++ sort of.

Anyways, I found a bug (I think) in partition-using. I'm using it [in real life](https://github.com/djhaskin987/degasolv/blob/feature/debian-pkg-system/src/degasolv/pkgsys/apt.clj#L36), but to stick to the example in my SO question for simplicity, I think I have isolated the bug with this case:

```clojure
(defn start-segment? [vals]
  (zero? (rem (first vals) 3)))

(partition-using start-segment? [3 6 7 9])
; => IllegalArgumentException colls must be all same type; found types=[clojure.lang.LazySeq nil]  tupelo.core/glue (core.cljc:533)

```

**Comment by cloojure** [comment]
Ah, yes. The perils of forgetting the behavior of `rest` vs `next`:

```clojure
(rest [1]) => ()
(next [1]) => nil
```

**Comment by cloojure** [comment]
OK, the fix is pushed!  Thank you for noticing!  I also added a new testcase:

```clojure
  (testing "partition-using"
    (let [start-segment? (fn [vals] (zero? (rem (first vals) 3))) ]
      (is= (partition-using start-segment? [1 2 3 6 7 8])
        [[1 2] [3] [6 7 8]])
      (is= (partition-using start-segment? [3 6 7 9])
        [[3] [6 7] [9]])
      (is= (partition-using start-segment? [1 2 3 6 7 8 9 12 13 15 16 17 18 18 18 3 4 5])
        [[1 2] [3] [6 7 8] [9] [12 13] [15 16 17] [18] [18] [18] [3 4 5]]))
    (throws? (partition-using even? 5)))
```

**Comment by cloojure** [comment]
[tupelo "0.9.30"] is on clojars

**Comment by djha-skin** [comment]
Yay! Thanks for the fix. I was impressed when looking through your unit tests this morning :)
