### ISSUE TITLE
Tupelo turns on schema fn validation

### ISSUE THREAD

**Issue by gfredericks** [cloojure/tupelo#9]
I was trying to figure out why my application was so slow when deployed, and it turns out that all my schemas were being validated at runtime when I didn't want them to be, due to `tupelo.core` calling `schema.core/set-fn-validation!` at the top of the file.

I think this sort of thing is better as opt-in.

**Comment by cloojure** [comment]
Good point, I meant that to only apply during testing.  I'll fix it.
Alan

**Comment by cloojure** [comment]
Release 0.9.32 is pushed to clojars.

**Comment by gfredericks** [comment]
Great, thanks!
